export const SCREENS = {
  EditInfoHeight: 'EditInfoHeight',
  EditInfoNickname: 'EditInfoNickname',
  EditInfoWeight: 'EditInfoWeight',
  DATING_NEARBY_FILTER: 'DATING_NEARBY_FILTER',
  CREATE_BASIC_PROFILE: 'CREATE_BASIC_PROFILE',
  CREATE_BASIC_PHOTOS: 'CREATE_BASIC_PHOTOS',
  Home: 'Home',
  LikedMe: 'LikedMe',
  Main: 'Main',
  Messages: 'Messages',
  ProfileEdit: 'ProfileEdit',
  ProfileNearby: 'ProfileNearby',
  ProfileSetting: 'ProfileSetting',
  SelectRelationshipGoal: 'SelectRelationshipGoal',
  SignIn: 'SignIn',
  SignInWithOtpPhoneNumber: 'SignInWithOtpPhoneNumber',
  SignInWithPhoneNumber: 'SignInWithPhoneNumber',
  Welcome: 'Welcome',
  ChatProfile: 'ChatProfile',
  LikedMeProfile: 'LikedMeProfile',
  DATING_SWIPE_PROFILE: 'DATING_SWIPE_PROFILE',
  EDIT_INFO_LOCATION: 'EDIT_INFO_LOCATION',
  SUBJECTS: 'SUBJECTS',
  SUBJECT: 'SUBJECT',
} as const;

export const AGES = {
  MIN: 18,
  MAX: 100,
};
